# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Monsieur Robi
email: bonjour@monsieurrobi.com
description: > # this means to ignore newlines until "baseurl:"
  Envie de vivre une expérience inédite ? Laissez-vous embarquer dans l'univers de Monsieur Robi et ses balades entrainantes et aérées !
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://monsieurrobi.com" # the base hostname & protocol for your site

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]
future: true
